---
- name: playbook_zsh.yml - zsh and oh-my-zsh setup
  hosts: all

  tasks:
    - name: install base zsh and curl
      become: yes
      pacman:
        update_cache: yes
        name:
          - zsh
          - curl
          - ranger
          - lsd
          - bat
          - xclip

    - name: change shell
      become: yes
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh

    - name: clone dotfiles
      git:
        repo: https://github.com/husseljoo/dotfiles.git
        dest: $HOME/dotfiles/

    - name: Install Oh My Zsh
      shell:
        cmd: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'

    - name: Clone zsh-syntax-highlighting plugin
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/

    - name: Clone zsh-autosuggestions plugin
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions/

    - name: Clone zsh-multiline theme
      git:
        repo: https://github.com/jan-auer/zsh-multiline.git
        dest: $HOME/.oh-my-zsh/custom/themes/zsh-multiline/

    - name: add my .zshrc
      copy:
        src: /home/husseljo/dotfiles/zshrc
        dest: /home/husseljo/.zshrc
        mode: 0644
