---
- name: playbook_nvim.yml - neovim set up
  hosts: all
  become: no

  tasks:
    - name: install neovim
      become: yes
      pacman:
        update_cache: yes
        name:
          - neovim

    - name: clone dotfiles
      git:
        repo: https://github.com/husseljoo/dotfiles.git
        dest: $HOME/dotfiles/

    - name: Create config directory if it does not exist
      file:
        path: $HOME/.config
        state: directory
        mode: "0755"

    - name: symlink neovim config
      become: no
      shell:
        cmd: "ln -s $HOME/dotfiles/nvim/ $HOME/.config/"

    - name: Create skeletons directory
      file:
        path: $HOME/.vim/templates/
        state: directory
        mode: "0755"

    - name: symlink skeletons config
      become: no
      shell:
        cmd: "ln -s $HOME/dotfiles/skeletons/ $HOME/.vim/templates/"
