---
- name: playbook_nvim.yml - neovim set up
  hosts: all
  become: no

  tasks:
    - name: install alacritty
      become: yes
      pacman:
        update_cache: yes
        name:
          - alacritty

    - name: clone dotfiles
      git:
        repo: git@github.com:husseljoo/dotfiles.git
        dest: ~

    - name: add alacritty config
      become: no
      copy:
        src: ~/dotfiles/alacritty.yml
        dest: ~/.config/alacritty/
        mode: 0644

    - name: add toggle script
      become: yes
      copy:
        src: ~/dotfiles/scripts/toggle_allacritty_opacity
        dest: /usr/bin/
        mode: 0644
