---
- name: playbook_install.yml - archlinux base setup
  hosts: all
  become: yes

  tasks:
    # ARCH FULL UPDATE  ----------------------------------------------------------

    - name: update arch
      pacman:
        update_cache: yes
        upgrade: yes

    # INSTALL VARIOUS PACKAGES  --------------------------------------------------

    - name: install bunch of packages
      pacman:
        update_cache: yes
        name:
          - base-devel
          - net-tools
          - zsh

    # SET HOSTNAME  ---------------------------------------------------------------

    # - name: generate fstab
    #   become: yes
    #   shell:
    #     cmd: "genfstab -U -p /mnt >> /mnt/etc/fstab"

    - name: set locale
      become: yes
      shell:
        cmd: "sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen"

    - name: set locale
      become: yes
      shell:
        cmd: "echo 'LANG=en_US.UTF-8' > /etc/locale.conf"

    - name: set timezone
      become: yes
      shell:
        cmd: "ln -sf /usr/share/zoneinfo/Africa/Cairo /etc/localtime"

    # - name: set local time
    #   become: yes
    #   shell:
    #     cmd: "hwclock --systohc --utc"

    # - name: Set hostname
    #   hostname:
    #     name: gang

    - name: set hostname
      become: yes
      shell:
        cmd: "echo -e '127.0.0.1\tlocalhost\n::1\tlocalhost\n127.0.1.1\tgang' | tee /etc/hosts"

    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Add the user 'husseljo' with a zsh shell, appending the group 'wheel' to the user's groups
      user:
        name: husseljo
        shell: /bin/bash
        password: $6$RvoVX8w1r4P1x1Dq$y2RnrsBMf5nZ2Nd8JHLnARttoN/FGddFHjNjdD66YymU3tWrvN6jPLZ0WUInnLRzh92VxJ0xAyYwFN1iYaxOi/
        groups: wheel
        append: yes
