---
- name: playbook_core.yml - archlinux base setup
  hosts: all
  become: yes

  tasks:
    # ARCH FULL UPDATE  ----------------------------------------------------------

    - name: update arch
      pacman:
        update_cache: yes
        upgrade: yes

    # INSTALL VARIOUS PACKAGES  --------------------------------------------------

    - name: install bunch of packages
      pacman:
        update_cache: yes
        name:
          - linux
          - linux-firmware
          - base
          - base-devel
          - sudo
          - git
          - curl
          - wget
          - lsd
          - ranger
          - fzf
          - bat
          - tree
          - xclip
          - duf
          - ncdu
          - htop
          - iotop
          - glances
          - reflector
          - networkmanager
          - zathura
          - man
          - brightnessctl

    #     # SYSTEM SETTINGS CHANGES ----------------------------------------------------

    - name: pacman - enable color
      lineinfile:
        path: /etc/pacman.conf
        regexp: "^#Color$"
        line: "Color"

    - name: pacman - enable ParallelDownloads = 5
      lineinfile:
        path: /etc/pacman.conf
        regexp: "#ParallelDownloads = 5"
        line: "ParallelDownloads = 5"

    - name: makepkg - disable compression
      lineinfile:
        path: /etc/makepkg.conf
        regexp: "PKGEXT='.pkg.tar.zst'"
        line: "PKGEXT='.pkg.tar'"

    - name: makepkg - enable parallel compilation MAKEFLAGS="-j$(nproc)"
      lineinfile:
        path: /etc/makepkg.conf
        regexp: '#MAKEFLAGS="-j2"'
        line: 'MAKEFLAGS="-j$(nproc)"'

    - name: fstab change relatime to noatime
      replace:
        path: /etc/fstab
        regexp: "relatime"
        replace: "noatime"

    - name: change number of failed logins that triger 10min lockout
      lineinfile:
        path: /etc/security/faillock.conf
        regexp: "^# deny = 3$"
        line: "deny = 10"

    #     # NEOFETCH  ------------------------------------------------------------------

    - name: install neofetch
      pacman:
        name:
          - neofetch

    - name: run neofetch to generate config
      become: no
      command: neofetch

    - name: enable disk info and IP in neofetch
      become: no
      lineinfile:
        path: ~/.config/neofetch/config.conf
        regexp: "{{item.From}}"
        line: "{{item.To}}"
      with_items:
        - { From: '.*# info "Disk" disk$', To: '    info "Disk" disk' }
        - {
            From: '.*# info "Local IP" local_ip$',
            To: '    info "Local IP" local_ip',
          }
        - {
            From: '.*# info "Public IP" public_ip',
            To: '    info "Public IP" public_ip',
          }
# #  ---------------------------------------------------------------------------
