---
- name: playbook_zsh.yml - zsh and zim setup
  hosts: all

  tasks:
    - name: install base zsh and curl
      become: yes
      pacman:
        update_cache: yes
        name:
          - zsh
          - curl

    - name: change shell
      become: yes
      user:
        name: "{{ ansible_user }}"
        shell: /bin/zsh

    - name: Install Oh My Zsh
      shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
      args:
        executable: /bin/bash

    - name: Clone zsh-syntax-highlighting plugin
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

    - name: Clone zsh-autosuggestions plugin
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

    - name: Clone zsh-multiline theme
      git:
        repo: https://github.com/jan-auer/zsh-multiline
        dest: ~/.oh-my-zsh/themes/zsh-multiline
