---
- name: playbook_nvim.yml - neovim set up
  hosts: all
  become: no

  tasks:
    - name: install alacritty
      become: yes
      pacman:
        update_cache: yes
        name:
          - alacritty

    - name: clone dotfiles
      git:
        repo: https://github.com/husseljoo/dotfiles.git
        dest: $HOME/dotfiles/

    - name: add alacritty config
      become: no
      copy:
        src: /home/husseljo/dotfiles/alacritty.yml
        dest: /home/husseljo/.config/alacritty/
        mode: 0644

    - name: add toggle scripts
      become: yes
      copy:
        src: /home/husseljo/dotfiles/scripts/toggle_allacritty_opacity
        dest: /usr/bin/toggle_allacritty_opacity
        mode: a+x
