---
- name: playbook_zsh.yml - zsh and zim setup
  hosts: all

  tasks:
    - name: install base zsh and curl
      become: yes
      pacman:
        update_cache: yes
        name:
          - zsh
          - curl

    - name: change shell
      become: yes
      user:
        name: "{{ ansible_user }}"
        shell: /bin/zsh

    - name: clone dotfiles
      git:
        repo: git@github.com:husseljoo/dotfiles.git
        dest: ~

    - name: Check if dotfiles exits is a Git repo
      stat:
        path: ~/dotfiles.git
      register: git_directory

    - name: add my .zshrc
      become: no
      copy:
        src: ~/dotfiles/zshrc
        dest: ~/.zshrc
        mode: 0644

    - name: Install Oh My Zsh
      shell:
        cmd: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'

    - name: Clone zsh-syntax-highlighting plugin
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

    - name: Clone zsh-autosuggestions plugin
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

    - name: Clone zsh-multiline theme
      git:
        repo: https://github.com/jan-auer/zsh-multiline
        dest: ~/.oh-my-zsh/themes/zsh-multiline
